specVersion: 0.2.0
name: zoommarket-subquery
version: 1.0.0
description: Zoom NFT Market on Moonbase
repository: https://github.com/ryanprice/zoommarket-subquery
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527" # Genesis hash of Moonbase
  # endpoint: wss://wss.api.moonbase.moonbeam.network
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  dictionary: "https://api.subquery.network/sq/subquery/moonbase-alpha-dictionary"

  chaintypes:
    file: "./types.yaml"

dataSources:
  - kind: substrate/Moonbeam
    startBlock: 1785000
    processor:
      file: "./node_modules/@subql/contract-processors/dist/moonbeam.js"
      options:
        # Must be a key of assets
        abi: "market"
        address: "0xd00d7b22deD10Fde1c94Be9E6D55D7190CCADD7F"
    assets:
      market:
        file: "./ZoombiesMarketPlace.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleTokenWhiteListedEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - tokenWhiteListed(address token, bool isWhitelisted, uint minBidIncrement)

        - handler: handleNftWhiteListed
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - nftWhiteListed(address token, bool isWhitelisted)

        - handler: handleMaxNFTCountChanged
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - maxNFTCountChanged(uint256 newMaxNFTCount)

        - handler: handleZoomBurnFeeChanged
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - zoomBurnFeeChanged(uint256 newZoomBurnFee)

        - handler: handleAuctionMaxTimeChanged
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - auctionMaxTimeChanged(uint256 newMaxAuctionTime);

        - handler: handleItemListed
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - ItemListed(uint256 indexed itemNumber, uint256 auctionEnd, address indexed seller, uint256[] tokenIds, address saleToken, address indexed nftToken, uint256 minPrice, uint256 zoomBurned)

        - handler: handleBidPlaced
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Bid(uint256 indexed itemNumber, uint256 bidAmount, address indexed bidder, uint256[] tokenIds)

        - handler: handleItemSettled
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Settled(uint256 indexed itemNumber, address nftToken, address saleToken, uint256 bidAmount, address indexed winner, address indexed seller, address royaltyReceiver, uint256 royaltyAmount, uint256[] tokenIds)
